import { TemplatePreset } from '@/types/editor';

export const TEMPLATE_PRESETS: TemplatePreset[] = [
    // ===== MINIMAL TEMPLATES =====
    {
        id: 'minimal-white',
        name: 'Pure White',
        description: 'Clean white background',
        category: 'minimal',
        preview: {
            backgroundType: 'solid',
            backgroundColor: '#ffffff',
        },
        settings: {
            backgroundType: 'solid',
            backgroundColor: '#ffffff',
            padding: 64,        // Free tier preset
            shadowBlur: 20,     // Free tier default
            shadowOpacity: 50,  // Free tier default
            borderRadius: 12,   // Free tier preset
            imageScale: 0.75,   // Within free range (50-150%)
        },
    },
    {
        id: 'minimal-dark',
        name: 'Dark Slate',
        description: 'Minimal dark background',
        category: 'minimal',
        preview: {
            backgroundType: 'solid',
            backgroundColor: '#1e293b',
        },
        settings: {
            backgroundType: 'solid',
            backgroundColor: '#1e293b',
            padding: 64,        // Free tier preset
            shadowBlur: 20,     // Free tier default
            shadowOpacity: 50,  // Free tier default
            borderRadius: 12,   // Free tier preset
            imageScale: 0.7,    // Within free range (50-150%)
        },
    },
    {
        id: 'minimal-charcoal',
        name: 'Charcoal',
        description: 'Deep charcoal background',
        category: 'minimal',
        preview: {
            backgroundType: 'solid',
            backgroundColor: '#18181b',
        },
        settings: {
            backgroundType: 'solid',
            backgroundColor: '#18181b',
            padding: 150,         // Premium setting
            shadowBlur: 35,       // Premium setting
            shadowOpacity: 40,    // Premium setting
            borderRadius: 20,     // Premium setting
            imageScale: 0.72,     // Within range
        },
    },
    {
        id: 'minimal-cream',
        name: 'Cream',
        description: 'Soft cream background',
        category: 'minimal',
        preview: {
            backgroundType: 'solid',
            backgroundColor: '#fefce8',
        },
        settings: {
            backgroundType: 'solid',
            backgroundColor: '#fefce8',
            padding: 130,         // Premium setting
            shadowBlur: 18,       // Premium setting
            shadowOpacity: 35,    // Premium setting
            borderRadius: 10,     // Premium setting
            imageScale: 0.78,     // Within range
        },
    },
    {
        id: 'minimal-navy',
        name: 'Navy',
        description: 'Deep navy background',
        category: 'minimal',
        preview: {
            backgroundType: 'solid',
            backgroundColor: '#0f172a',
        },
        settings: {
            backgroundType: 'solid',
            backgroundColor: '#0f172a',
            padding: 155,         // Premium setting
            shadowBlur: 32,       // Premium setting
            shadowOpacity: 45,    // Premium setting
            borderRadius: 14,     // Premium setting
            imageScale: 0.7,      // Within range
        },
    },
    {
        id: 'minimal-stone',
        name: 'Stone',
        description: 'Neutral stone background',
        category: 'minimal',
        preview: {
            backgroundType: 'solid',
            backgroundColor: '#78716c',
        },
        settings: {
            backgroundType: 'solid',
            backgroundColor: '#78716c',
            padding: 145,         // Premium setting
            shadowBlur: 25,       // Premium setting
            shadowOpacity: 30,    // Premium setting
            borderRadius: 16,     // Premium setting
            imageScale: 0.73,     // Within range
        },
    },

    // ===== VIBRANT GRADIENTS =====
    {
        id: 'vibrant-sunset',
        name: 'Sunset Glow',
        description: 'Vibrant orange to pink gradient',
        category: 'vibrant',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#f97316', '#ec4899'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#f97316', '#ec4899'],
            gradientAngle: 135,
            padding: 64,          // Free tier preset
            shadowBlur: 20,       // Free tier default
            shadowOpacity: 50,    // Free tier default
            borderRadius: 12,     // Free tier preset
            imageScale: 0.75,     // Within free range (50-150%)
            // Removed text overlay - free tier has limited text options
        },
    },
    {
        id: 'vibrant-ocean',
        name: 'Ocean Waves',
        description: 'Blue to purple gradient',
        category: 'vibrant',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#0ea5e9', '#8b5cf6'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#0ea5e9', '#8b5cf6'],
            gradientAngle: 135,
            padding: 96,          // Free tier preset
            shadowBlur: 20,       // Free tier default
            shadowOpacity: 50,    // Free tier default
            borderRadius: 24,     // Free tier preset
            imageScale: 0.8,      // Within free range (50-150%)
        },
    },
    {
        id: 'vibrant-neon',
        name: 'Neon Nights',
        description: 'Electric purple to pink',
        category: 'vibrant',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#7928ca', '#ff0080'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#7928ca', '#ff0080'],
            gradientAngle: 135,
            padding: 180,
            shadowBlur: 40,
            shadowOpacity: 50,
            borderRadius: 24,
            imageScale: 0.7,
            textOverlays: [
                {
                    text: 'LIVE',
                    x: 50,
                    y: 88,
                    color: '#ffffff',
                    fontSize: 56,
                    fontFamily: 'Righteous, sans-serif',
                    fontWeight: 400,
                },
            ],
        },
    },
    {
        id: 'vibrant-fire',
        name: 'Fire',
        description: 'Red to orange gradient',
        category: 'vibrant',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#dc2626', '#f97316'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#dc2626', '#f97316'],
            gradientAngle: 135,
            padding: 165,
            shadowBlur: 28,
            shadowOpacity: 35,
            borderRadius: 18,
            imageScale: 0.72,
        },
    },
    {
        id: 'vibrant-mint',
        name: 'Mint Fresh',
        description: 'Teal to green gradient',
        category: 'vibrant',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#14b8a6', '#22c55e'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#14b8a6', '#22c55e'],
            gradientAngle: 135,
            padding: 155,
            shadowBlur: 25,
            shadowOpacity: 30,
            borderRadius: 16,
            imageScale: 0.74,
        },
    },
    {
        id: 'vibrant-candy',
        name: 'Candy',
        description: 'Pink to purple candy gradient',
        category: 'vibrant',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#f472b6', '#a855f7'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#f472b6', '#a855f7'],
            gradientAngle: 135,
            padding: 170,
            shadowBlur: 30,
            shadowOpacity: 35,
            borderRadius: 20,
            imageScale: 0.7,
            textOverlays: [
                {
                    text: 'SWEET',
                    x: 50,
                    y: 88,
                    color: '#ffffff',
                    fontSize: 60,
                    fontFamily: 'Fredoka, sans-serif',
                    fontWeight: 600,
                },
            ],
        },
    },
    {
        id: 'vibrant-electric',
        name: 'Electric',
        description: 'Cyan to blue gradient',
        category: 'vibrant',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#06b6d4', '#3b82f6'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#06b6d4', '#3b82f6'],
            gradientAngle: 135,
            padding: 160,
            shadowBlur: 32,
            shadowOpacity: 40,
            borderRadius: 18,
            imageScale: 0.73,
        },
    },
    {
        id: 'vibrant-golden',
        name: 'Golden Hour',
        description: 'Yellow to orange gradient',
        category: 'vibrant',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#eab308', '#f97316'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#eab308', '#f97316'],
            gradientAngle: 135,
            padding: 155,
            shadowBlur: 26,
            shadowOpacity: 32,
            borderRadius: 16,
            imageScale: 0.74,
        },
    },

    // ===== PROFESSIONAL =====
    {
        id: 'professional-royal',
        name: 'Royal Purple',
        description: 'Professional gradient with title text',
        category: 'professional',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#6366f1', '#8b5cf6'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#6366f1', '#8b5cf6'],
            gradientAngle: 135,
            padding: 150,
            shadowBlur: 20,
            shadowOpacity: 25,
            borderRadius: 12,
            imageScale: 0.75,
            textOverlays: [
                {
                    text: 'PORTFOLIO',
                    x: 50,
                    y: 90,
                    color: '#ffffff',
                    fontSize: 80,
                    fontFamily: '"Playfair Display", serif',
                    fontWeight: 700,
                },
            ],
        },
    },
    {
        id: 'professional-corporate',
        name: 'Corporate Blue',
        description: 'Clean blue gradient',
        category: 'professional',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#3b82f6', '#1d4ed8'],
            gradientAngle: 180,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#3b82f6', '#1d4ed8'],
            gradientAngle: 180,
            padding: 140,
            shadowBlur: 15,
            shadowOpacity: 20,
            borderRadius: 8,
            imageScale: 0.75,
        },
    },
    {
        id: 'professional-slate',
        name: 'Slate',
        description: 'Dark slate gradient',
        category: 'professional',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#334155', '#1e293b'],
            gradientAngle: 180,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#334155', '#1e293b'],
            gradientAngle: 180,
            padding: 145,
            shadowBlur: 22,
            shadowOpacity: 35,
            borderRadius: 10,
            imageScale: 0.74,
        },
    },
    {
        id: 'professional-emerald',
        name: 'Emerald',
        description: 'Professional green gradient',
        category: 'professional',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#059669', '#047857'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#059669', '#047857'],
            gradientAngle: 135,
            padding: 150,
            shadowBlur: 20,
            shadowOpacity: 28,
            borderRadius: 12,
            imageScale: 0.73,
            textOverlays: [
                {
                    text: 'GROWTH',
                    x: 50,
                    y: 90,
                    color: '#ffffff',
                    fontSize: 72,
                    fontFamily: 'Montserrat, sans-serif',
                    fontWeight: 700,
                },
            ],
        },
    },
    {
        id: 'professional-rose',
        name: 'Rose',
        description: 'Elegant rose gradient',
        category: 'professional',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#e11d48', '#be123c'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#e11d48', '#be123c'],
            gradientAngle: 135,
            padding: 155,
            shadowBlur: 24,
            shadowOpacity: 30,
            borderRadius: 14,
            imageScale: 0.72,
        },
    },
    {
        id: 'professional-indigo',
        name: 'Indigo',
        description: 'Deep indigo gradient',
        category: 'professional',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#4f46e5', '#3730a3'],
            gradientAngle: 180,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#4f46e5', '#3730a3'],
            gradientAngle: 180,
            padding: 148,
            shadowBlur: 22,
            shadowOpacity: 28,
            borderRadius: 12,
            imageScale: 0.74,
            textOverlays: [
                {
                    text: 'PREMIUM',
                    x: 50,
                    y: 90,
                    color: '#ffffff',
                    fontSize: 68,
                    fontFamily: 'Inter, sans-serif',
                    fontWeight: 800,
                },
            ],
        },
    },
    {
        id: 'professional-amber',
        name: 'Amber',
        description: 'Warm amber gradient',
        category: 'professional',
        preview: {
            backgroundType: 'gradient',
            gradientColors: ['#d97706', '#b45309'],
            gradientAngle: 135,
        },
        settings: {
            backgroundType: 'gradient',
            gradientColors: ['#d97706', '#b45309'],
            gradientAngle: 135,
            padding: 152,
            shadowBlur: 20,
            shadowOpacity: 26,
            borderRadius: 12,
            imageScale: 0.74,
        },
    },

    // ===== CREATIVE MESH GRADIENTS =====
    {
        id: 'creative-aurora',
        name: 'Aurora Dreams',
        description: 'Multi-color mesh gradient',
        category: 'creative',
        preview: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 40% 20%, #4f46e5 0px, transparent 50%), radial-gradient(at 80% 0%, #f472b6 0px, transparent 50%), radial-gradient(at 0% 50%, #0ea5e9 0px, transparent 50%), radial-gradient(at 80% 50%, #22c55e 0px, transparent 50%), radial-gradient(at 0% 100%, #f97316 0px, transparent 50%), radial-gradient(at 80% 100%, #8b5cf6 0px, transparent 50%)',
        },
        settings: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 40% 20%, #4f46e5 0px, transparent 50%), radial-gradient(at 80% 0%, #f472b6 0px, transparent 50%), radial-gradient(at 0% 50%, #0ea5e9 0px, transparent 50%), radial-gradient(at 80% 50%, #22c55e 0px, transparent 50%), radial-gradient(at 0% 100%, #f97316 0px, transparent 50%), radial-gradient(at 80% 100%, #8b5cf6 0px, transparent 50%)',
            padding: 180,
            shadowBlur: 35,
            shadowOpacity: 40,
            borderRadius: 24,
            imageScale: 0.65,
        },
    },
    {
        id: 'creative-cosmic',
        name: 'Cosmic Space',
        description: 'Deep space colors',
        category: 'creative',
        preview: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 0% 0%, #1e3a8a 0px, transparent 50%), radial-gradient(at 100% 0%, #7c3aed 0px, transparent 50%), radial-gradient(at 100% 100%, #ec4899 0px, transparent 50%), radial-gradient(at 0% 100%, #0891b2 0px, transparent 50%)',
        },
        settings: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 0% 0%, #1e3a8a 0px, transparent 50%), radial-gradient(at 100% 0%, #7c3aed 0px, transparent 50%), radial-gradient(at 100% 100%, #ec4899 0px, transparent 50%), radial-gradient(at 0% 100%, #0891b2 0px, transparent 50%)',
            padding: 170,
            shadowBlur: 40,
            shadowOpacity: 45,
            borderRadius: 20,
            imageScale: 0.7,
            textOverlays: [
                {
                    text: 'SPACE',
                    x: 50,
                    y: 50,
                    color: '#ffffff',
                    fontSize: 96,
                    fontFamily: 'Anton, sans-serif',
                    fontWeight: 400,
                },
            ],
        },
    },
    {
        id: 'creative-sunset-mesh',
        name: 'Sunset Mesh',
        description: 'Warm sunset mesh',
        category: 'creative',
        preview: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 0% 0%, #f97316 0px, transparent 50%), radial-gradient(at 100% 0%, #ec4899 0px, transparent 50%), radial-gradient(at 50% 100%, #8b5cf6 0px, transparent 50%)',
        },
        settings: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 0% 0%, #f97316 0px, transparent 50%), radial-gradient(at 100% 0%, #ec4899 0px, transparent 50%), radial-gradient(at 50% 100%, #8b5cf6 0px, transparent 50%)',
            padding: 165,
            shadowBlur: 32,
            shadowOpacity: 38,
            borderRadius: 20,
            imageScale: 0.68,
        },
    },
    {
        id: 'creative-ocean-mesh',
        name: 'Ocean Mesh',
        description: 'Cool ocean mesh',
        category: 'creative',
        preview: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 0% 50%, #0ea5e9 0px, transparent 50%), radial-gradient(at 100% 50%, #06b6d4 0px, transparent 50%), radial-gradient(at 50% 0%, #3b82f6 0px, transparent 50%), radial-gradient(at 50% 100%, #8b5cf6 0px, transparent 50%)',
        },
        settings: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 0% 50%, #0ea5e9 0px, transparent 50%), radial-gradient(at 100% 50%, #06b6d4 0px, transparent 50%), radial-gradient(at 50% 0%, #3b82f6 0px, transparent 50%), radial-gradient(at 50% 100%, #8b5cf6 0px, transparent 50%)',
            padding: 175,
            shadowBlur: 35,
            shadowOpacity: 42,
            borderRadius: 22,
            imageScale: 0.66,
        },
    },
    {
        id: 'creative-neon-mesh',
        name: 'Neon Mesh',
        description: 'Electric neon mesh',
        category: 'creative',
        preview: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 20% 20%, #7c3aed 0px, transparent 50%), radial-gradient(at 80% 20%, #ec4899 0px, transparent 50%), radial-gradient(at 50% 80%, #06b6d4 0px, transparent 50%)',
        },
        settings: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 20% 20%, #7c3aed 0px, transparent 50%), radial-gradient(at 80% 20%, #ec4899 0px, transparent 50%), radial-gradient(at 50% 80%, #06b6d4 0px, transparent 50%)',
            padding: 170,
            shadowBlur: 38,
            shadowOpacity: 45,
            borderRadius: 24,
            imageScale: 0.67,
            textOverlays: [
                {
                    text: 'GLOW',
                    x: 50,
                    y: 50,
                    color: '#ffffff',
                    fontSize: 88,
                    fontFamily: 'Bungee, sans-serif',
                    fontWeight: 400,
                },
            ],
        },
    },
    {
        id: 'creative-forest-mesh',
        name: 'Forest Mesh',
        description: 'Natural forest mesh',
        category: 'creative',
        preview: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 0% 0%, #22c55e 0px, transparent 50%), radial-gradient(at 100% 0%, #14b8a6 0px, transparent 50%), radial-gradient(at 50% 100%, #059669 0px, transparent 50%)',
        },
        settings: {
            backgroundType: 'mesh',
            meshGradientCSS: 'radial-gradient(at 0% 0%, #22c55e 0px, transparent 50%), radial-gradient(at 100% 0%, #14b8a6 0px, transparent 50%), radial-gradient(at 50% 100%, #059669 0px, transparent 50%)',
            padding: 160,
            shadowBlur: 30,
            shadowOpacity: 35,
            borderRadius: 18,
            imageScale: 0.7,
        },
    },

    // ===== WAVE SPLIT DESIGNS =====
    {
        id: 'wave-sunset',
        name: 'Wave Sunset',
        description: 'Orange gradient with white wave',
        category: 'wave',
        preview: {
            backgroundType: 'waveSplit',
            gradientColors: ['#f97316', '#ec4899'],
            backgroundColor: '#ffffff',
            waveSplitFlipped: false,
        },
        settings: {
            backgroundType: 'waveSplit',
            gradientColors: ['#f97316', '#ec4899'],
            gradientAngle: 135,
            backgroundColor: '#ffffff',
            waveSplitFlipped: false,
            padding: 150,
            shadowBlur: 25,
            shadowOpacity: 30,
            borderRadius: 16,
            imageScale: 0.75,
            textOverlays: [
                {
                    text: 'SUNSET',
                    x: 50,
                    y: 88,
                    color: '#ffffff',
                    fontSize: 72,
                    fontFamily: 'Oswald, sans-serif',
                    fontWeight: 700,
                },
            ],
        },
    },
    {
        id: 'wave-ocean',
        name: 'Wave Ocean',
        description: 'Blue gradient wave split',
        category: 'wave',
        preview: {
            backgroundType: 'waveSplit',
            gradientColors: ['#0ea5e9', '#3b82f6'],
            backgroundColor: '#1e293b',
            waveSplitFlipped: true,
        },
        settings: {
            backgroundType: 'waveSplit',
            gradientColors: ['#0ea5e9', '#3b82f6'],
            gradientAngle: 135,
            backgroundColor: '#1e293b',
            waveSplitFlipped: true,
            padding: 160,
            shadowBlur: 30,
            shadowOpacity: 35,
            borderRadius: 20,
            imageScale: 0.7,
            textOverlays: [
                {
                    text: 'OCEAN',
                    x: 50,
                    y: 12,
                    color: '#ffffff',
                    fontSize: 72,
                    fontFamily: 'Montserrat, sans-serif',
                    fontWeight: 800,
                },
            ],
        },
    },
    {
        id: 'wave-forest',
        name: 'Wave Forest',
        description: 'Green gradient with dark split',
        category: 'wave',
        preview: {
            backgroundType: 'waveSplit',
            gradientColors: ['#22c55e', '#14b8a6'],
            backgroundColor: '#0f172a',
            waveSplitFlipped: false,
        },
        settings: {
            backgroundType: 'waveSplit',
            gradientColors: ['#22c55e', '#14b8a6'],
            gradientAngle: 135,
            backgroundColor: '#0f172a',
            waveSplitFlipped: false,
            padding: 170,
            shadowBlur: 28,
            shadowOpacity: 32,
            borderRadius: 18,
            imageScale: 0.7,
            textOverlays: [
                {
                    text: 'NATURE',
                    x: 50,
                    y: 88,
                    color: '#ffffff',
                    fontSize: 72,
                    fontFamily: 'Poppins, sans-serif',
                    fontWeight: 700,
                },
            ],
        },
    },
    {
        id: 'wave-purple',
        name: 'Wave Purple',
        description: 'Purple gradient wave',
        category: 'wave',
        preview: {
            backgroundType: 'waveSplit',
            gradientColors: ['#8b5cf6', '#6366f1'],
            backgroundColor: '#18181b',
            waveSplitFlipped: true,
        },
        settings: {
            backgroundType: 'waveSplit',
            gradientColors: ['#8b5cf6', '#6366f1'],
            gradientAngle: 135,
            backgroundColor: '#18181b',
            waveSplitFlipped: true,
            padding: 160,
            shadowBlur: 28,
            shadowOpacity: 35,
            borderRadius: 18,
            imageScale: 0.72,
        },
    },
    {
        id: 'wave-rose',
        name: 'Wave Rose',
        description: 'Pink rose wave',
        category: 'wave',
        preview: {
            backgroundType: 'waveSplit',
            gradientColors: ['#ec4899', '#f472b6'],
            backgroundColor: '#fdf4ff',
            waveSplitFlipped: false,
        },
        settings: {
            backgroundType: 'waveSplit',
            gradientColors: ['#ec4899', '#f472b6'],
            gradientAngle: 135,
            backgroundColor: '#fdf4ff',
            waveSplitFlipped: false,
            padding: 155,
            shadowBlur: 24,
            shadowOpacity: 28,
            borderRadius: 16,
            imageScale: 0.73,
            textOverlays: [
                {
                    text: 'LOVE',
                    x: 50,
                    y: 88,
                    color: '#ffffff',
                    fontSize: 76,
                    fontFamily: '"Dancing Script", cursive',
                    fontWeight: 700,
                },
            ],
        },
    },
    {
        id: 'wave-dark-blue',
        name: 'Wave Midnight',
        description: 'Dark blue wave',
        category: 'wave',
        preview: {
            backgroundType: 'waveSplit',
            gradientColors: ['#1e40af', '#3b82f6'],
            backgroundColor: '#0f172a',
            waveSplitFlipped: false,
        },
        settings: {
            backgroundType: 'waveSplit',
            gradientColors: ['#1e40af', '#3b82f6'],
            gradientAngle: 135,
            backgroundColor: '#0f172a',
            waveSplitFlipped: false,
            padding: 165,
            shadowBlur: 30,
            shadowOpacity: 38,
            borderRadius: 20,
            imageScale: 0.7,
        },
    },
    {
        id: 'wave-warm',
        name: 'Wave Warm',
        description: 'Warm orange wave',
        category: 'wave',
        preview: {
            backgroundType: 'waveSplit',
            gradientColors: ['#dc2626', '#f97316'],
            backgroundColor: '#fffbeb',
            waveSplitFlipped: true,
        },
        settings: {
            backgroundType: 'waveSplit',
            gradientColors: ['#dc2626', '#f97316'],
            gradientAngle: 135,
            backgroundColor: '#fffbeb',
            waveSplitFlipped: true,
            padding: 158,
            shadowBlur: 26,
            shadowOpacity: 32,
            borderRadius: 18,
            imageScale: 0.72,
            textOverlays: [
                {
                    text: 'HOT',
                    x: 50,
                    y: 12,
                    color: '#ffffff',
                    fontSize: 80,
                    fontFamily: 'Anton, sans-serif',
                    fontWeight: 400,
                },
            ],
        },
    },

    // ===== TEXT PATTERN DESIGNS =====
    {
        id: 'text-welcome',
        name: 'Welcome Text',
        description: 'Pink gradient with WELCOME text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#f472b6', '#c084fc'],
            gradientAngle: 135,
            textPatternText: 'WELCOME',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#f472b6', '#c084fc'],
            gradientAngle: 135,
            textPatternText: 'WELCOME',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.1,
            textPatternPositions: ['center'],
            textPatternFontFamily: '"Playfair Display", serif', // Free tier font
            textPatternFontSize: 0.35,
            textPatternFontWeight: 700,
            padding: 64,          // Free tier preset
            shadowBlur: 20,       // Free tier default
            shadowOpacity: 50,    // Free tier default
            borderRadius: 12,     // Free tier preset
            imageScale: 0.75,     // Within free range (50-150%)
        },
    },
    {
        id: 'text-creative',
        name: 'Creative Text',
        description: 'Purple gradient with CREATIVE text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#8b5cf6', '#6366f1'],
            gradientAngle: 135,
            textPatternText: 'CREATIVE',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#8b5cf6', '#6366f1'],
            gradientAngle: 135,
            textPatternText: 'CREATIVE',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.09,
            textPatternPositions: ['center'],
            textPatternFontFamily: 'Montserrat, sans-serif', // Free tier font
            textPatternFontSize: 0.35,
            textPatternFontWeight: 700, // Changed to 700 (free tier weight)
            padding: 96,          // Free tier preset
            shadowBlur: 20,       // Free tier default
            shadowOpacity: 50,    // Free tier default
            borderRadius: 24,     // Free tier preset
            imageScale: 0.8,      // Within free range (50-150%)
        },
    },
    {
        id: 'text-brand',
        name: 'Brand Text',
        description: 'Orange to pink with BRAND text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#f97316', '#ec4899'],
            gradientAngle: 135,
            textPatternText: 'BRAND',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#f97316', '#ec4899'],
            gradientAngle: 135,
            textPatternText: 'BRAND',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.1,
            textPatternPositions: ['top', 'bottom'],
            textPatternFontFamily: 'Montserrat, sans-serif',
            textPatternFontSize: 0.35,
            textPatternFontWeight: 900,
            padding: 180,
            shadowBlur: 30,
            shadowOpacity: 35,
            borderRadius: 24,
            imageScale: 0.7,
            textOverlays: [
                {
                    text: 'Your Brand',
                    x: 50,
                    y: 50,
                    color: '#ffffff',
                    fontSize: 88,
                    fontFamily: '"Playfair Display", serif',
                    fontWeight: 700,
                },
            ],
        },
    },
    {
        id: 'text-launch',
        name: 'Launch Text',
        description: 'Red gradient with LAUNCH text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#ef4444', '#f97316'],
            gradientAngle: 135,
            textPatternText: 'LAUNCH',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#ef4444', '#f97316'],
            gradientAngle: 135,
            textPatternText: 'LAUNCH',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.1,
            textPatternPositions: ['center'],
            textPatternFontFamily: '"Archivo Black", sans-serif',
            textPatternFontSize: 0.35,
            textPatternFontWeight: 400,
            padding: 170,
            shadowBlur: 28,
            shadowOpacity: 32,
            borderRadius: 20,
            imageScale: 0.7,
        },
    },
    {
        id: 'text-sale',
        name: 'Sale Text',
        description: 'Blue gradient with SALE text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#3b82f6', '#06b6d4'],
            gradientAngle: 135,
            textPatternText: 'SALE',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#3b82f6', '#06b6d4'],
            gradientAngle: 135,
            textPatternText: 'SALE',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.12,
            textPatternPositions: ['top', 'bottom'],
            textPatternFontFamily: '"Bebas Neue", sans-serif',
            textPatternFontSize: 0.4,
            textPatternFontWeight: 400,
            padding: 165,
            shadowBlur: 26,
            shadowOpacity: 30,
            borderRadius: 18,
            imageScale: 0.72,
            textOverlays: [
                {
                    text: '50% OFF',
                    x: 50,
                    y: 50,
                    color: '#ffffff',
                    fontSize: 72,
                    fontFamily: 'Anton, sans-serif',
                    fontWeight: 400,
                },
            ],
        },
    },
    {
        id: 'text-new',
        name: 'New Text',
        description: 'Green gradient with NEW text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#22c55e', '#14b8a6'],
            gradientAngle: 135,
            textPatternText: 'NEW',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#22c55e', '#14b8a6'],
            gradientAngle: 135,
            textPatternText: 'NEW',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.1,
            textPatternPositions: ['center'],
            textPatternFontFamily: 'Poppins, sans-serif',
            textPatternFontSize: 0.45,
            textPatternFontWeight: 700,
            padding: 160,
            shadowBlur: 24,
            shadowOpacity: 28,
            borderRadius: 16,
            imageScale: 0.73,
        },
    },
    {
        id: 'text-hot',
        name: 'Hot Text',
        description: 'Red to pink with HOT text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#dc2626', '#ec4899'],
            gradientAngle: 135,
            textPatternText: 'HOT',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#dc2626', '#ec4899'],
            gradientAngle: 135,
            textPatternText: 'HOT',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.12,
            textPatternPositions: ['top', 'center', 'bottom'],
            textPatternFontFamily: 'Anton, sans-serif',
            textPatternFontSize: 0.5,
            textPatternFontWeight: 400,
            padding: 175,
            shadowBlur: 30,
            shadowOpacity: 35,
            borderRadius: 22,
            imageScale: 0.68,
        },
    },
    {
        id: 'text-vip',
        name: 'VIP Text',
        description: 'Gold gradient with VIP text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#d97706', '#eab308'],
            gradientAngle: 135,
            textPatternText: 'VIP',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#d97706', '#eab308'],
            gradientAngle: 135,
            textPatternText: 'VIP',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.1,
            textPatternPositions: ['center'],
            textPatternFontFamily: '"Playfair Display", serif',
            textPatternFontSize: 0.5,
            textPatternFontWeight: 700,
            padding: 165,
            shadowBlur: 28,
            shadowOpacity: 32,
            borderRadius: 20,
            imageScale: 0.7,
            textOverlays: [
                {
                    text: 'EXCLUSIVE',
                    x: 50,
                    y: 50,
                    color: '#ffffff',
                    fontSize: 64,
                    fontFamily: 'Montserrat, sans-serif',
                    fontWeight: 700,
                },
            ],
        },
    },
    {
        id: 'text-best',
        name: 'Best Text',
        description: 'Indigo gradient with BEST text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#4f46e5', '#7c3aed'],
            gradientAngle: 135,
            textPatternText: 'BEST',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#4f46e5', '#7c3aed'],
            gradientAngle: 135,
            textPatternText: 'BEST',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.1,
            textPatternPositions: ['top', 'bottom'],
            textPatternFontFamily: 'Oswald, sans-serif',
            textPatternFontSize: 0.4,
            textPatternFontWeight: 700,
            padding: 168,
            shadowBlur: 27,
            shadowOpacity: 33,
            borderRadius: 18,
            imageScale: 0.71,
        },
    },

    // ===== TEXT REPEAT PATTERNS (Wallpaper Style) =====
    {
        id: 'text-repeat-design',
        name: 'Design Repeat',
        description: 'Wallpaper pattern with DESIGN text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#7c3aed', '#ec4899'],
            gradientAngle: 135,
            textPatternText: 'DESIGN',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#7c3aed', '#ec4899'],
            gradientAngle: 135,
            textPatternText: 'DESIGN',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.08,
            textPatternRows: 6,
            textPatternFontFamily: '"Bebas Neue", sans-serif',
            textPatternFontSize: 0.35,
            textPatternFontWeight: 400,
            padding: 160,
            shadowBlur: 28,
            shadowOpacity: 35,
            borderRadius: 20,
            imageScale: 0.7,
        },
    },
    {
        id: 'text-repeat-code',
        name: 'Code Repeat',
        description: 'Developer wallpaper with CODE text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#0f172a', '#1e293b'],
            gradientAngle: 180,
            textPatternText: 'CODE',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#0f172a', '#1e293b'],
            gradientAngle: 180,
            textPatternText: 'CODE',
            textPatternColor: '#22c55e',
            textPatternOpacity: 0.12,
            textPatternRows: 8,
            textPatternFontFamily: '"JetBrains Mono", monospace',
            textPatternFontSize: 0.35,
            textPatternFontWeight: 700,
            padding: 150,
            shadowBlur: 25,
            shadowOpacity: 40,
            borderRadius: 16,
            imageScale: 0.72,
        },
    },
    {
        id: 'text-repeat-love',
        name: 'Love Repeat',
        description: 'Romantic wallpaper with LOVE text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#ec4899', '#f472b6'],
            gradientAngle: 135,
            textPatternText: 'LOVE',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#ec4899', '#f472b6'],
            gradientAngle: 135,
            textPatternText: 'LOVE',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.1,
            textPatternRows: 5,
            textPatternFontFamily: '"Dancing Script", cursive',
            textPatternFontSize: 0.4,
            textPatternFontWeight: 700,
            padding: 165,
            shadowBlur: 26,
            shadowOpacity: 30,
            borderRadius: 18,
            imageScale: 0.7,
        },
    },
    {
        id: 'text-repeat-shop',
        name: 'Shop Repeat',
        description: 'E-commerce wallpaper with SHOP text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#f97316', '#eab308'],
            gradientAngle: 135,
            textPatternText: 'SHOP',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#f97316', '#eab308'],
            gradientAngle: 135,
            textPatternText: 'SHOP',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.1,
            textPatternRows: 7,
            textPatternFontFamily: 'Anton, sans-serif',
            textPatternFontSize: 0.35,
            textPatternFontWeight: 400,
            padding: 170,
            shadowBlur: 30,
            shadowOpacity: 35,
            borderRadius: 20,
            imageScale: 0.68,
            textOverlays: [
                {
                    text: 'NOW',
                    x: 50,
                    y: 50,
                    color: '#ffffff',
                    fontSize: 80,
                    fontFamily: 'Anton, sans-serif',
                    fontWeight: 400,
                },
            ],
        },
    },
    {
        id: 'text-repeat-music',
        name: 'Music Repeat',
        description: 'Audio wallpaper with MUSIC text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#6366f1', '#8b5cf6'],
            gradientAngle: 135,
            textPatternText: 'MUSIC',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#6366f1', '#8b5cf6'],
            gradientAngle: 135,
            textPatternText: 'MUSIC',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.09,
            textPatternRows: 6,
            textPatternFontFamily: 'Righteous, sans-serif',
            textPatternFontSize: 0.35,
            textPatternFontWeight: 400,
            padding: 160,
            shadowBlur: 28,
            shadowOpacity: 32,
            borderRadius: 18,
            imageScale: 0.7,
        },
    },
    {
        id: 'text-repeat-studio',
        name: 'Studio Repeat',
        description: 'Creative studio wallpaper',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#18181b', '#27272a'],
            gradientAngle: 180,
            textPatternText: 'STUDIO',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#18181b', '#27272a'],
            gradientAngle: 180,
            textPatternText: 'STUDIO',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.06,
            textPatternRows: 5,
            textPatternFontFamily: 'Montserrat, sans-serif',
            textPatternFontSize: 0.35,
            textPatternFontWeight: 800,
            padding: 155,
            shadowBlur: 30,
            shadowOpacity: 45,
            borderRadius: 16,
            imageScale: 0.72,
        },
    },
    {
        id: 'text-repeat-tech',
        name: 'Tech Repeat',
        description: 'Technology wallpaper with TECH text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#0ea5e9', '#06b6d4'],
            gradientAngle: 135,
            textPatternText: 'TECH',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#0ea5e9', '#06b6d4'],
            gradientAngle: 135,
            textPatternText: 'TECH',
            textPatternColor: '#ffffff',
            textPatternOpacity: 0.1,
            textPatternRows: 8,
            textPatternFontFamily: 'Orbitron, sans-serif',
            textPatternFontSize: 0.35,
            textPatternFontWeight: 700,
            padding: 160,
            shadowBlur: 26,
            shadowOpacity: 32,
            borderRadius: 18,
            imageScale: 0.7,
        },
    },
    {
        id: 'text-repeat-premium',
        name: 'Premium Repeat',
        description: 'Luxury wallpaper with PREMIUM text',
        category: 'text',
        preview: {
            backgroundType: 'textPattern',
            gradientColors: ['#78350f', '#92400e'],
            gradientAngle: 135,
            textPatternText: 'PREMIUM',
        },
        settings: {
            backgroundType: 'textPattern',
            gradientColors: ['#78350f', '#92400e'],
            gradientAngle: 135,
            textPatternText: 'PREMIUM',
            textPatternColor: '#fcd34d',
            textPatternOpacity: 0.12,
            textPatternRows: 4,
            textPatternFontFamily: '"Playfair Display", serif',
            textPatternFontSize: 0.35,
            textPatternFontWeight: 700,
            padding: 165,
            shadowBlur: 28,
            shadowOpacity: 38,
            borderRadius: 20,
            imageScale: 0.7,
            textOverlays: [
                {
                    text: 'QUALITY',
                    x: 50,
                    y: 50,
                    color: '#fcd34d',
                    fontSize: 64,
                    fontFamily: '"Playfair Display", serif',
                    fontWeight: 700,
                },
            ],
        },
    },
];

// Group templates by category for easier navigation
export const TEMPLATES_BY_CATEGORY = {
    minimal: TEMPLATE_PRESETS.filter(t => t.category === 'minimal'),
    vibrant: TEMPLATE_PRESETS.filter(t => t.category === 'vibrant'),
    professional: TEMPLATE_PRESETS.filter(t => t.category === 'professional'),
    creative: TEMPLATE_PRESETS.filter(t => t.category === 'creative'),
    wave: TEMPLATE_PRESETS.filter(t => t.category === 'wave'),
    text: TEMPLATE_PRESETS.filter(t => t.category === 'text'),
};
